# Introducción a las ciencias de la computación *y programación en Python*

*Banco de Guatemala*  
*PES 2025-2026*  
*Programación I*  
*Septiembre de 2025*  

## Abstract

> "*I do not fear computers. I fear lack of them.*" **Isaac Asimov**

- Paquete de computación científica NumPy

    - Introducción
    
    - Conceptos básicos de utilización
    
    - Ejercicios

# NumPy

- Paquete de Python para **computación científica** de **alto desempeño** sobre vectores, matrices y estructuras de mayores dimensiones (tensores).

- Implementado en C y Fortran, por lo que cuando se **vectorizan** las oepraciones, el desempeño es muy bueno.

- Ofrece una estructura de datos `ndarray` para procesar de forma **eficiente** datos homogéneos.

- Capacidades de algebra lineal, transformada de Fourier y generación de números aleatorios.

## Pero, ¿y las listas de Python?

- Las listas son muy generales, pueden contener cualquier tipo de objeto.

    - Implementan tipos dinámicos.
    
    - No permiten operaciones matemáticas como la *multiplicación matricial* o *producto punto*.
    
- Los vectores de NumPy son de tipado estático y homogéneo. El tipo del arreglo se determina cuando se crea el vector.

    - Son eficientes en memoria.
    
    - Es posible implementar **funciones universales** (ufuncs). 
    
    - El tipado estático permite implementar operaciones matemáticas de forma eficiente a través de C y Fortran.
    

In [2]:
[[1,2],[3,4]] * [1,2]

TypeError: can't multiply sequence by non-int of type 'list'

In [4]:
def f(x):
    return 2*x + 1

f([2,3,4])

TypeError: can only concatenate list (not "int") to list

### Comparación entre lenguajes de programación

![julia-benchmarks.svg](figs/numpy/julia-benchmarks.svg)

[5 Razones para aprender NumPy](https://insights.dice.com/2016/09/01/5-reasons-know-numpy/): 

    It's fast
    It works very well with SciPy and other Libraries
    It lets you do matrix arithmetic
    It has lots of built-in functions
    It has universal functions


## Importando NumPy

In [5]:
import numpy as np

- Revisamos la versión de NumPy (importante al ver la documentación)

In [6]:
np.__version__

'2.2.6'

### Obteniendo ayuda

In [7]:
# Obtiene una ventana de ayuda
np.ndarray?

Init signature: np.ndarray(self, /, *args, **kwargs)
Docstring:     
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer int

In [9]:
np.array

<function numpy.array>

In [8]:
# Función help para una función
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

***
## La clase `ndarray`

In [11]:
x = np.array([1,2,3])
type(x)

numpy.ndarray

- La clase básica de NumPy se llama `ndarray` (alias `array`). Sus atributos más importantes son: 

    - `ndarray.ndim` : número de dimensiones del arreglo.

    - `ndarray.shape` : dimensiones del arreglo. Esta es una **tupla de enteros** que indica el tamaño de la matriz en cada dimensión. Para una matriz con $n$ filas y $m$ columnas, la forma será $(n, m)$. La longitud de la tupla de forma es, por lo tanto, el número de ejes, `ndim`.

    - `darray.size` : el número total de elementos del arreglo. Es igual al producto de los elementos de la tupla `shape`.

    - `ndarray.dtype` : un **objeto** que describe el **tipo** de los elementos en el arreglo. Es posible crear y especificar `dtypes` propios.
        - Adicionalmente, NumPy provee algunos tipos propios muy utilizados: `numpy.int32`, `numpy.int16`, and `numpy.float64`.

    - `ndarray.itemsize` : el tamaño en bytes de cada elemento en el arreglo. Por ejemplo, un arreglo de tipo `float64` tiene tamaño en bytes de $8 (=64/8)$. Equivalente a `ndarray.dtype.itemsize`.

    - `ndarray.data` : el búfer que contiene los elementos del arreglo. Aunque normalmente, no accedemos al atributo directamente, ya que hacemos uso de los elementos con *slicing*.



In [25]:
a = np.arange(15, dtype='float64').reshape(3, 5)
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [34]:
a.shape

(3, 5)

In [35]:
a.ndim

2

In [28]:
a.dtype
# type(a.dtype)

dtype('float64')

In [29]:
a.dtype.name

'float64'

In [30]:
a.itemsize

8

In [31]:
a.data

In [32]:
a.size

15

In [33]:
type(a)

numpy.ndarray

***
# Creando arreglos N-dimensionales de NumPy

- Hay varias formas de inicializar nuevas matrices numpy, por ejemplo desde

    - Una lista de Python o tuplas.
    
    - Utilizando funciones dedicadas a **generar** arreglos de NumPy.

      - Es común inicializar vectores de ceros o con valores aleatorios.
    
    - Leer información de archivos. 

In [40]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [41]:
a.dtype

dtype('int64')

In [42]:
b = np.array([1.2, 3.5, 5.1])
b

array([1.2, 3.5, 5.1])

In [43]:
b.dtype

dtype('float64')

In [45]:
c = np.array([1.,2,3])
c

array([1., 2., 3.])

### Error frecuente

Crear el arreglo con varios argumentos en vez de proveer una sola lista o secuencia como argumento

In [47]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the 

In [46]:
# Error frecuente
a = np.array(1,2,3,4)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [51]:
a = np.array([1,2,3,4], dtype='int16')
a

array([1, 2, 3, 4], dtype=int16)

## A partir de listas o tuplas 
`ndarray` transforma secuencias de secuencias en matrices bidimensionales, secuencias de secuencias de secuencias en matrices tridimensionales, etc.

In [52]:
b = np.array([[1.5,2,3], [4,5,6]])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [55]:
b = np.array([ [[1.5,2], [4,5]], [[1,2], [3,4]]])
b

array([[[1.5, 2. ],
        [4. , 5. ]],

       [[1. , 2. ],
        [3. , 4. ]]])

In [57]:
b = np.array([
    [ [[1.5,2], [4,5]], [[1,2], [3,4]]], 
    [ [[1.5,2], [4,5]], [[1,2], [3,4]]]
])
b

array([[[[1.5, 2. ],
         [4. , 5. ]],

        [[1. , 2. ],
         [3. , 4. ]]],


       [[[1.5, 2. ],
         [4. , 5. ]],

        [[1. , 2. ],
         [3. , 4. ]]]])

El tipo de matriz también se puede especificar explícitamente en el momento de la creación:

In [58]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

## Funciones de generación de arreglos

In [59]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [60]:
# A diferencia de range
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [61]:
np.linspace(0, 100, 10000)

array([0.00000000e+00, 1.00010001e-02, 2.00020002e-02, ...,
       9.99799980e+01, 9.99899990e+01, 1.00000000e+02], shape=(10000,))

In [62]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [68]:
np.zeros((10,10,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],


In [66]:
np.ones?

Signature: np.ones(shape, dtype=None, order='C', *, device=None, like=None)
Docstring:
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In thi

#### Evaluación de funciones

Notar que la evaluación de funciones es "vectorizada", es decir, sobre todos los elementos del arreglo a la vez. 

- ¡Evitamos los ciclos `for` de Python porque son más lentos!

In [72]:
T = 1000

In [73]:
x = np.linspace(0, 2*np.pi, T)
x

array([0.        , 0.00628947, 0.01257895, 0.01886842, 0.0251579 ,
       0.03144737, 0.03773685, 0.04402632, 0.0503158 , 0.05660527,
       0.06289475, 0.06918422, 0.0754737 , 0.08176317, 0.08805265,
       0.09434212, 0.1006316 , 0.10692107, 0.11321055, 0.11950002,
       0.1257895 , 0.13207897, 0.13836845, 0.14465792, 0.15094739,
       0.15723687, 0.16352634, 0.16981582, 0.17610529, 0.18239477,
       0.18868424, 0.19497372, 0.20126319, 0.20755267, 0.21384214,
       0.22013162, 0.22642109, 0.23271057, 0.23900004, 0.24528952,
       0.25157899, 0.25786847, 0.26415794, 0.27044742, 0.27673689,
       0.28302637, 0.28931584, 0.29560531, 0.30189479, 0.30818426,
       0.31447374, 0.32076321, 0.32705269, 0.33334216, 0.33963164,
       0.34592111, 0.35221059, 0.35850006, 0.36478954, 0.37107901,
       0.37736849, 0.38365796, 0.38994744, 0.39623691, 0.40252639,
       0.40881586, 0.41510534, 0.42139481, 0.42768429, 0.43397376,
       0.44026323, 0.44655271, 0.45284218, 0.45913166, 0.46542

In [74]:
y = np.sin(x)
y 

array([ 0.00000000e+00,  6.28943332e-03,  1.25786178e-02,  1.88673048e-02,
        2.51552454e-02,  3.14421909e-02,  3.77278927e-02,  4.40121020e-02,
        5.02945704e-02,  5.65750492e-02,  6.28532900e-02,  6.91290446e-02,
        7.54020646e-02,  8.16721019e-02,  8.79389084e-02,  9.42022363e-02,
        1.00461838e-01,  1.06717465e-01,  1.12968871e-01,  1.19215809e-01,
        1.25458030e-01,  1.31695289e-01,  1.37927338e-01,  1.44153931e-01,
        1.50374822e-01,  1.56589764e-01,  1.62798512e-01,  1.69000820e-01,
        1.75196443e-01,  1.81385136e-01,  1.87566653e-01,  1.93740751e-01,
        1.99907185e-01,  2.06065711e-01,  2.12216086e-01,  2.18358066e-01,
        2.24491409e-01,  2.30615871e-01,  2.36731210e-01,  2.42837185e-01,
        2.48933554e-01,  2.55020076e-01,  2.61096510e-01,  2.67162616e-01,
        2.73218154e-01,  2.79262883e-01,  2.85296566e-01,  2.91318963e-01,
        2.97329837e-01,  3.03328948e-01,  3.09316061e-01,  3.15290939e-01,
        3.21253344e-01,  

In [80]:
%%timeit
y = np.sin(x)

8.3 μs ± 235 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [81]:
%%timeit 
y2 = np.zeros(T)
for i in range(len(x)):
    xi = x[i]
    y2[i] = np.sin(xi)

1.34 ms ± 170 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


##  Variables aleatorias

In [82]:
b = np.random.random((5, 5))
b

array([[3.19503319e-01, 8.48880415e-01, 7.27544496e-01, 6.00807043e-05,
        3.53521966e-01],
       [9.06803034e-01, 5.16840413e-01, 3.45874020e-01, 9.09777818e-01,
        2.28914291e-01],
       [7.71109910e-01, 8.97127913e-01, 8.61218615e-01, 5.11860581e-01,
        5.73153465e-01],
       [2.23203910e-02, 9.66105537e-01, 3.75012347e-01, 5.39493617e-02,
        6.77702163e-01],
       [5.20644170e-01, 3.99119344e-01, 9.12016710e-01, 6.77066269e-01,
        1.43693639e-01]])

## Unos, ceros

In [83]:
np.zeros([10, 10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [84]:
np.ones([5, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [85]:
# Copiando la forma de x
np.ones_like(x)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [86]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Desde archivos

In [87]:
data = np.loadtxt("data/data.csv", delimiter=',', skiprows=1)
data

array([[1.00000000e+00, 3.44899870e-01],
       [2.00000000e+00, 9.31072695e-01],
       [3.00000000e+00, 6.25704035e-01],
       [4.00000000e+00, 8.41599361e-01],
       [5.00000000e+00, 8.87112967e-01],
       [6.00000000e+00, 5.58222238e-01],
       [7.00000000e+00, 3.05687170e-02],
       [8.00000000e+00, 7.21006651e-01],
       [9.00000000e+00, 2.15081930e-02],
       [1.00000000e+01, 4.89341526e-01],
       [1.10000000e+01, 3.23284084e-01],
       [1.20000000e+01, 1.86885658e-01],
       [1.30000000e+01, 4.64906445e-01],
       [1.40000000e+01, 5.60553301e-01],
       [1.50000000e+01, 3.83349378e-01],
       [1.60000000e+01, 4.76682101e-01],
       [1.70000000e+01, 9.40387708e-01],
       [1.80000000e+01, 4.03836182e-01],
       [1.90000000e+01, 8.30264821e-01],
       [2.00000000e+01, 2.50129241e-01],
       [2.10000000e+01, 5.85427477e-01],
       [2.20000000e+01, 9.33801603e-01],
       [2.30000000e+01, 6.32389807e-01],
       [2.40000000e+01, 1.85051348e-01],
       [2.500000

***
# Impresión de arreglos

Cuando imprimes una matriz, NumPy la muestra de forma similar a las listas anidadas, pero con el siguiente diseño:

- el último eje se imprime de izquierda a derecha,

- el penúltimo se imprime de arriba a abajo,

- el resto también se imprime de arriba a abajo, con cada corte separado del siguiente por una línea vacía.

Las matrices unidimensionales se imprimen como filas, bidimensionales como matrices y tridimensionales como listas de matrices.

In [91]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [94]:
a.shape

(4, 4)

In [88]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [95]:
b = np.array([
    [ [[1.5,2], [4,5]], [[1,2], [3,4]]], 
    [ [[1.5,2], [4,5]], [[1,2], [3,4]]]
])
b

array([[[[1.5, 2. ],
         [4. , 5. ]],

        [[1. , 2. ],
         [3. , 4. ]]],


       [[[1.5, 2. ],
         [4. , 5. ]],

        [[1. , 2. ],
         [3. , 4. ]]]])

In [96]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [97]:
c = np.arange(24).reshape(2,3,4) 
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [98]:
# Si es muy grande, se suprime parte de la salida
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [99]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


***
# Operaciones básicas

Las operaciones básicas son aplicadas elemento a elemento (*elementwise*). Se crea un nuevo arreglo lleno con el resultado

In [100]:
a = np.array( [20,30,40,50] )
b = np.arange(4)
a, b

(array([20, 30, 40, 50]), array([0, 1, 2, 3]))

In [101]:
c = a - b
c

array([20, 29, 38, 47])

`*` opera en sentido elemento a elemento sobre los arreglos.

In [103]:
a*b

array([  0,  30,  80, 150])

In [104]:
# Constante por arreglo
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [107]:
a

array([20, 30, 40, 50])

In [110]:
# Arreglos lógicos
a < 35

array([ True,  True, False, False])

La multiplicación matricial puede hacerse utilizando `@` o el método `dot`

In [111]:
A = np.array( [[1, 1], [0, 1]] )
B = np.array( [[2, 0], [3, 4]] )

In [112]:
A * B

array([[2, 0],
       [0, 4]])

In [119]:
A @ B

array([[5, 4],
       [3, 4]])

In [115]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [120]:
np.matmul(A, B)

array([[5, 4],
       [3, 4]])

In [121]:
b = np.random.random((2,3))
b

array([[0.06108971, 0.61888647, 0.35705625],
       [0.83231658, 0.45864597, 0.83045078]])

Operadores `+=` y `*=` son válidos para modificar arreglos existentes.

In [122]:
a = np.ones((2,3), dtype=int)
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [124]:
b = np.random.random((2,3))
b += a 
b

array([[3.89805782, 3.28750691, 3.43495223],
       [3.71278341, 3.19852295, 3.00442716]])

## Métodos útiles

In [125]:
a = np.random.random((2, 3))
a

array([[0.13479703, 0.58589737, 0.14673818],
       [0.8898179 , 0.26787626, 0.24184777]])

In [127]:
a.sum() # equivalente a np.sum(a)

np.float64(2.266974501296758)

In [128]:
a.min()

np.float64(0.13479702657657933)

In [129]:
a.max()

np.float64(0.8898179009428776)

Por defecto operan sobre el arreglo como si fueran una lista de números. Es posible especificar el eje sobre el cuál se desea aplicar la operación con el parámetro `axis`

In [133]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
b.sum()

np.int64(66)

In [135]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# Suma de las columnas 
b.sum(axis=0)

array([12, 15, 18, 21])

In [141]:
# Vector fila: agregamos dimensiones
b.sum(axis=0)[np.newaxis, :]

array([[12, 15, 18, 21]])

In [146]:
# Mínimo de cada fila
b.min(axis=1).shape

(3,)

In [147]:
# Mínimo de cada fila
b.min(axis=1)[:, np.newaxis].shape

(3, 1)

In [148]:
# Suma acumulada en las columnas 
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [150]:
b.max(axis=0)

array([ 8,  9, 10, 11])

***
## Funciones universales (*ufuncs*)

In [151]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [152]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [153]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

Podemos definir funciones de usuario que sean universales: $$ f(x) = 2x + e^x - \sqrt{x} $$

In [154]:
def f(x):
    return 2*x + np.exp(x) - np.sqrt(x)

In [155]:
a

array([0, 1, 2, 3, 4])

In [156]:
f(2)

np.float64(9.974842536557555)

In [157]:
f(a)

array([ 1.        ,  3.71828183,  9.97484254, 24.35348612, 60.59815003])

***
## Indexing, Slicing and Iterating

Los arreglos unidimensionales se pueden indexar, dividir e iterar, al igual que las listas y otras secuencias de Python.

In [162]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [161]:
a.size

10

In [163]:
a[2]

np.int64(8)

In [165]:
a[2:5]

array([ 8, 27, 64])

In [169]:
# Asignación múltiple
a[0:6:2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [168]:
for i in range(0, 6, 2): 
    a[i] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [172]:
def f(x,y):
    return 10*x + y

In [173]:
b = np.fromfunction(f, (5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [174]:
b[x][y]

IndexError: arrays used as indices must be of integer (or boolean) type

In [176]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [182]:
b[:, 2]

array([ 2, 12, 22, 32, 42])

In [183]:
b[2, :]

array([20, 21, 22, 23])

In [192]:
b

array([[ 0,  1,  2,  3],
       [10,  1, 12, 13],
       [20,  1, 22, 23],
       [30,  1, 32, 33],
       [40,  1, 42, 43]])

In [193]:
b[0:5, 1] = 1

In [194]:
b[:, 1]

array([1, 1, 1, 1, 1])

Cuando se proporcionan menos índices que el número de ejes, los índices faltantes se consideran segmentos completos `:`

In [195]:
b

array([[ 0,  1,  2,  3],
       [10,  1, 12, 13],
       [20,  1, 22, 23],
       [30,  1, 32, 33],
       [40,  1, 42, 43]])

In [196]:
# Ultima fila, todas las columnas
b[-1]

array([40,  1, 42, 43])

In [205]:
b[-4, -4] == b[1, 0]

np.True_

In [200]:
np.ones((4,3,2,1))

array([[[[1.],
         [1.]],

        [[1.],
         [1.]],

        [[1.],
         [1.]]],


       [[[1.],
         [1.]],

        [[1.],
         [1.]],

        [[1.],
         [1.]]],


       [[[1.],
         [1.]],

        [[1.],
         [1.]],

        [[1.],
         [1.]]],


       [[[1.],
         [1.]],

        [[1.],
         [1.]],

        [[1.],
         [1.]]]])

La iteración sobre arreglos multidimensionales se realiza con respecto al primer eje

In [218]:
b = np.ones((10,3,3))
np.min(b, axis=(0,1))

array([1., 1., 1.])

In [212]:
for row in b:
    print(row)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Sin embargo, si se desea realizar una operación en cada elemento de la matriz, se puede usar el atributo `flat` que es un iterador sobre todos los elementos de la matriz:

In [220]:
b

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [222]:
b.flat

In [219]:
for element in b.flat:
    print(element)

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [223]:
b.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.])

***
## Manipulación del `shape` (forma) del arreglo

Una matriz tiene una forma dada por el número de elementos a lo largo de cada eje:

In [224]:
a = np.floor ( 10 * np.random.random (( 3 , 4 )))
a

array([[2., 8., 5., 3.],
       [6., 3., 6., 7.],
       [4., 6., 8., 4.]])

In [225]:
a.shape

(3, 4)

La forma de una matriz se puede cambiar con varios comandos. Tenga en cuenta que los siguientes tres comandos devuelven una matriz modificada, pero **no cambian la matriz original**:

In [226]:
a.ravel()  # returns the array, flattened

array([2., 8., 5., 3., 6., 3., 6., 7., 4., 6., 8., 4.])

In [227]:
a.flatten()

array([2., 8., 5., 3., 6., 3., 6., 7., 4., 6., 8., 4.])

In [232]:
a.reshape(2, -1)  # returns the array with a modified shape

array([[2., 8., 5., 3., 6., 3.],
       [6., 7., 4., 6., 8., 4.]])

In [234]:
a

array([[2., 8., 5., 3.],
       [6., 3., 6., 7.],
       [4., 6., 8., 4.]])

In [235]:
a.T

array([[2., 6., 4.],
       [8., 3., 6.],
       [5., 6., 8.],
       [3., 7., 4.]])

In [236]:
a.T.shape

(4, 3)

In [240]:
a = np.ones([3,2,1])
a.shape

(3, 2, 1)

In [242]:
a.T
a.T.shape

(1, 2, 3)

- El orden de los elementos en la matriz resultante de `ravel()` es normalmente "estilo `C`", es decir, el índice de la derecha "cambia más rápido", por lo que el elemento después de un `[0,0]` es un `[0,1]`. 

- Si la matriz se reforma a otra forma, nuevamente la matriz se trata como "estilo `C`". NumPy normalmente crea matrices almacenadas en este orden, por lo que `ravel()` generalmente no necesitará copiar su argumento, pero si la matriz se hizo tomando segmentos de otra matriz o se creó con opciones inusuales, es posible que deba copiarse. 

- Las funciones `ravel()` y `reshape()` también se pueden instruir, utilizando un argumento opcional, para usar matrices de estilo FORTRAN, en las que el índice más a la izquierda cambia más rápido.

La función de `reshape` devuelve su argumento con una forma modificada, mientras que el método `ndarray.resize` modifica la matriz en sí:

In [ ]:
a

In [ ]:
a.resize((2, 6))
a

***
## Concatenación de arreglos
Se pueden apilar varios arreglos a lo largo de diferentes ejes:

In [245]:
a = np.floor(10*np.random.random((2,2)))
a

array([[5., 6.],
       [1., 9.]])

In [246]:
b = np.floor(10*np.random.random((2,2)))
b

array([[4., 5.],
       [7., 8.]])

In [247]:
# np.vstack pide una tupla de ndarrays 
np.vstack((a,b))

array([[5., 6.],
       [1., 9.],
       [4., 5.],
       [7., 8.]])

In [248]:
# np.hstack pide una tupla de ndarrays 
np.hstack((a,b))

array([[5., 6., 4., 5.],
       [1., 9., 7., 8.]])

In [249]:
np.column_stack((a,b)) # Equivalente a np.hstack para arreglos 2D

array([[5., 6., 4., 5.],
       [1., 9., 7., 8.]])

In [250]:
np.hstack((a,b)) 

array([[5., 6., 4., 5.],
       [1., 9., 7., 8.]])

- Cuando los arreglos son 1D, `np.column_stack()` y `np.hstack()` se comportan diferente

In [252]:
a = np.array([4.,2.])
b = np.array([3.,8.])

In [253]:
np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [254]:
np.hstack((a,b)) 

array([4., 2., 3., 8.])

- Podemos crear nuevas dimensiones en el arreglo con `np.newaxis` o con `None`

In [258]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [259]:
a[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

In [261]:
a[np.newaxis, :]

array([[1, 2, 3, 4]])

In [260]:
a[:, None]

array([[1],
       [2],
       [3],
       [4]])

In [262]:
np.column_stack((a[:, np.newaxis], b[:, np.newaxis]))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

- Por otro lado, la función `row_stack` es equivalente a `vstack` para cualquier arreglo de entrada. De hecho, `row_stack` es un alias para `vstack`

In [ ]:
np.row_stack is np.vstack

- En general, para arreglos con más de dos dimensiones:
    
    - `hstack` apila a lo largo del segundo eje, 
    
    - `vstack` apila a lo largo del primer eje y 
    
    - `concatenate` permite argumentos opcionales que dan el número del eje (`axis`) a lo largo del cual debe ocurrir la concatenación.

***
## Separar un arreglo en varios más pequeños

In [263]:
a = np.floor(10*np.random.random((2,12)))
a

array([[6., 5., 2., 0., 9., 5., 0., 5., 9., 2., 5., 4.],
       [9., 8., 2., 7., 7., 8., 5., 1., 1., 5., 9., 2.]])

In [265]:
np.hsplit(a,3)   # Split a into 3

[array([[6., 5., 2., 0.],
        [9., 8., 2., 7.]]),
 array([[9., 5., 0., 5.],
        [7., 8., 5., 1.]]),
 array([[9., 2., 5., 4.],
        [1., 5., 9., 2.]])]

In [267]:
np.hsplit(a, (3,4))   # Split a after the third and the fourth column

[array([[6., 5., 2.],
        [9., 8., 2.]]),
 array([[0.],
        [7.]]),
 array([[9., 5., 0., 5., 9., 2., 5., 4.],
        [7., 8., 5., 1., 1., 5., 9., 2.]])]

In [266]:
help(np.hsplit)

Help on _ArrayFunctionDispatcher in module numpy:

hsplit(ary, indices_or_sections)
    Split an array into multiple sub-arrays horizontally (column-wise).

    Please refer to the `split` documentation.  `hsplit` is equivalent
    to `split` with ``axis=1``, the array is always split along the second
    axis except for 1-D arrays, where it is split at ``axis=0``.

    See Also
    --------
    split : Split an array into multiple sub-arrays of equal size.

    Examples
    --------
    >>> import numpy as np
    >>> x = np.arange(16.0).reshape(4, 4)
    >>> x
    array([[ 0.,   1.,   2.,   3.],
           [ 4.,   5.,   6.,   7.],
           [ 8.,   9.,  10.,  11.],
           [12.,  13.,  14.,  15.]])
    >>> np.hsplit(x, 2)
    [array([[  0.,   1.],
           [  4.,   5.],
           [  8.,   9.],
           [12.,  13.]]),
     array([[  2.,   3.],
           [  6.,   7.],
           [10.,  11.],
           [14.,  15.]])]
    >>> np.hsplit(x, np.array([3, 6]))
    [array([[ 0.,   1

***
# Mutabilidad y clonado

Al operar y manipular arreglos, los datos a veces se copian en un nuevo arreglo y otras no. Esto es a menudo una fuente de confusión para los principiantes. 

Hay tres casos:

In [274]:
a = np.arange( 12 )
b = a
b is a

True

In [273]:
a.shape

(12,)

In [275]:
b.shape = 3, 4
a.shape

(3, 4)

1. Cortar una matriz devuelve una vista de ella:

In [276]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [279]:
s = a[:, 1:3] # Slicing genera copias
s

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [278]:
s is a

False

## Copia profunda 

El método de copy hace una copia completa de la matriz y sus datos.

In [281]:
# a new array object with new data is created
d = a.copy()
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [282]:
d is a

False

In [283]:
d == a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [284]:
np.all(d == a)

np.True_

***
# Rutinas de NumPy

[Rutinas y funcionalidad](https://numpy.org/devdocs/reference/routines.html#routines)

***
# Para usuarios ***pro*** (como ustedes)

## *Broadcasting* (difusión)

- Este mecanismo permite que las funciones universales manejen de manera significativa entradas que no tienen exactamente la misma forma.

[General Broadcasting Rules](https://numpy.org/devdocs/user/basics.broadcasting.html)

- Un ejemplo:

In [ ]:
x = np.arange(4)
x

In [ ]:
xx = x.reshape(4,1)
xx

In [ ]:
x + xx

In [ ]:
x.shape

In [ ]:
xx.shape

- El *broadcasting* proporciona una forma conveniente de tomar el producto externo (o cualquier otra operación externa) de dos matrices. El siguiente ejemplo muestra una operación de adición externa de dos matrices 1D:

In [ ]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])

In [ ]:
a[:, None] + b

Aquí, `None` inserta un nuevo eje en `a`, haciéndolo un arreglo bidimensional de `4x1`. Al combinar este arreglo de `4x1` con `b`, que tiene forma `(3,)`, resulta un arreglo de `4x3`

### ¿Por qué funciona?

- Cuando se operan dos arreglos, NumPy compara sus formas (`shape`) elemento a elemento, empezando por la última dimensión y hacia arriba. 

- Dos dimensiones son compatibles cuando:
    
    - Son iguales, o
    
    - Una de ellas es 1
    
- Cuando alguna de las dos dimensiones es uno, **se utiliza la otra**. 

    - En otras palabras, las dimensiones con tamaño 1 son "estiradas" o "copiadas" para ajustarse a la otra.

***
## *Fancy indexing* y trucos de indexación

- NumPy ofrece más funciones de indexación que las secuencias regulares de Python. Además de la indexación por enteros y sectores, como vimos antes, las matrices se pueden indexar por matrices de enteros y matrices de booleanos.

In [ ]:
a = np.arange(11)**2
a

In [ ]:
i = np.array( [ 1,1,3,8,5 ] )
i

In [ ]:
a[i]   # the elements of a at the positions i

In [ ]:
j = np.array([[ 3, 4], [ 9, 7 ]])  # a bidimensional array of indices
j

In [ ]:
a[j] # the same shape as j

- También podemos dar índices para más de una dimensión. Las matrices de índices para cada dimensión deben tener la misma forma.

In [ ]:
a = np.arange(12).reshape(3,4)
a

In [ ]:
i = np.array([[0,1], [1,2]])
j = np.array([[2,1], [3,3]])

In [ ]:
i

In [ ]:
j

In [ ]:
a[i,j] # i and j must have equal shape

In [ ]:
a[i,2]

In [ ]:
a[:,j]

***
### Búsqueda del máximo

In [ ]:
data = np.sin(np.arange(20)).reshape(5,4)
data

In [ ]:
# index of the maxima for each series
ind = data.argmax(axis=0)
ind

***
###  Asignación múltiple con indexación

In [ ]:
a = np.arange(5)
a

In [ ]:
a[[1,3,4]] = 0
a

In [ ]:
# Se queda la última asignación
a = np.arange(5)
a[[0,0,2]] = [1,2,3]
a

***
### Indexado con arreglos booleanos

- Cuando indexamos arreglos con otros arreglos de índices (enteros), proporcionamos la lista de índices para elegir. Con los índices booleanos, el enfoque es diferente; **elegimos explícitamente qué elementos de la matriz queremos y cuáles no**.

La forma más natural en la que uno puede pensar para la indexación booleana es usar matrices booleanas que tengan la misma forma que la matriz original:

In [ ]:
a = np.arange(12).reshape(3,4)
a

In [ ]:
b = a > 4
b

In [ ]:
a[b]

- También se puede utilizar en asignaciones:

In [ ]:
a[b] = 0
a

***
# Álgebra lineal

In [ ]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
a

In [ ]:
a.transpose()

In [ ]:
np.linalg.inv(a)

In [ ]:
np.eye(2)

In [ ]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])

j @ j

In [ ]:
y = np.array([[5.], [7.]])
y

In [ ]:
np.linalg.solve(a, y)

In [ ]:
# eigenvalores y eigenvectores
np.linalg.eig(a)

***
# Ejercicios propuestos

1. De las siguientes secciones, revisa las funciones de NumPy disponibles para darte una idea de lo que es posible hacer. 

    - [Array creation routines](https://numpy.org/devdocs/reference/routines.array-creation.html)

    - [Array manipulation routines](https://numpy.org/devdocs/reference/routines.array-manipulation.html)

    - [Binary operations](https://numpy.org/devdocs/reference/routines.bitwise.html)

    - [String operations](https://numpy.org/devdocs/reference/routines.char.html)
    

2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)
    
3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)    
    
4. Crear una función llamada `estimate` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 

    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 

    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

In [1]:
import numpy as np

In [9]:
T = 1000000
x = 2*np.random.rand(T) - 1
y = 2*np.random.rand(T) - 1

dentro = (x**2 + y**2 < 1**2).sum()
prop = dentro / T
prop

pi_approx = 4 * prop
pi_approx


np.float64(3.143768)